source 'https://rubygems.org'

gem 'activevalidators'
gem 'authie',                     '~> 1.1.0'
gem 'bcrypt',                     '~> 3.1.7'
gem 'chronic',                    '~> 0.10.2'
gem 'chronic_duration',           '~> 0.10'
gem 'coffee-rails',               '~> 4.1.0'
gem 'datey',                      '~> 1.0'
gem 'delayed_job_active_record'
gem 'dynamic_form'
gem 'florrick',                   '~> 1.1'
gem 'foreman'
gem 'haml',                       '~> 4.0.5'
gem 'jquery-rails'
gem 'kaminari',                   '~> 0.16.1'
gem 'rails',                      '4.2.0'
gem 'moonrope',                   '~> 1.3'
gem 'nifty-attachments'
gem 'nifty-utils',                '~> 1.1'
gem 'nilify_blanks',              '~> 1.1.0'
gem 'parallel'
gem 'pg'
gem 'premailer',                  '~> 1.8.3'
gem 'puma'
gem 'rails_env_config',           '~> 1'
gem 'redcarpet',                  '~> 3.2.2'
gem 'rest-client'
gem 'sass-rails',                 '~> 5.0'
gem 'uglifier',                   '>= 1.3.0'

group :development, :test do
  gem 'annotate',                 '~> 2.6.5'
  gem 'byebug'
  gem 'web-console',              '~> 2.0'
end
